version: "3.8"

services:
  dockerized-build:
    build:
      context: ..
      dockerfile: ./dockerized-build-env/Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /app
